config/routes.rb
Rails.application.routes.draw do

  resources :registrations
  resources :events
  resources :fests
  

end

app/models/event.rb
class Event < ActiveRecord::Base
	validates_presence_of :name, :fest_id, :entry_fee, :location, :start_datetime, :end_datetime 
end

app/models/fest.rb
class Fest < ActiveRecord::Base

	validates_presence_of :name, :description, :start_date, :end_date

	validate :check_end_date

	private

	def check_end_date

		if (!self.end_date.nil? && !self.start_date.nil?) && self.end_date < self.start_date
			errors.add(:end_date, "Cannot be less than the start date")
		end
	end

end

app/models/registration.rb
class Registration < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :entry_fee, :start_datetime, :end_datetime, :no_participants, :location, :fest_id)
    end
end

app/controllers/fests_controller.rb
class FestsController < ApplicationController
  before_action :set_fest, only: [:show, :edit, :update, :destroy]

  # GET /fests
  # GET /fests.json
  def index
    @fests = Fest.all
  end

  # GET /fests/1
  # GET /fests/1.json
  def show
  end

  # GET /fests/new
  def new
    @fest = Fest.new
  end

  # GET /fests/1/edit
  def edit
  end

  # POST /fests
  # POST /fests.json
  def create
    @fest = Fest.new(fest_params)

    respond_to do |format|
      if @fest.save
        format.html { redirect_to @fest, notice: 'Fest was successfully created.' }
        format.json { render :show, status: :created, location: @fest }
      else
        format.html { render :new }
        format.json { render json: @fest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fests/1
  # PATCH/PUT /fests/1.json
  def update
    respond_to do |format|
      if @fest.update(fest_params)
        format.html { redirect_to @fest, notice: 'Fest was successfully updated.' }
        format.json { render :show, status: :ok, location: @fest }
      else
        format.html { render :edit }
        format.json { render json: @fest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fests/1
  # DELETE /fests/1.json
  def destroy
    @fest.destroy
    respond_to do |format|
      format.html { redirect_to fests_url, notice: 'Fest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fest
      @fest = Fest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fest_params
      params.require(:fest).permit(:name, :description, :start_date, :end_date)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :set_registration, only: [:show, :edit, :update, :destroy]

  # GET /registrations
  # GET /registrations.json
  def index
    @registrations = Registration.all
  end

  # GET /registrations/1
  # GET /registrations/1.json
  def show
  end

  # GET /registrations/new
  def new
    @registration = Registration.new
  end

  # GET /registrations/1/edit
  def edit
  end

  # POST /registrations
  # POST /registrations.json
  def create
    @registration = Registration.new(registration_params)

    respond_to do |format|
      if @registration.save
        format.html { redirect_to @registration, notice: 'Registration was successfully created.' }
        format.json { render :show, status: :created, location: @registration }
      else
        format.html { render :new }
        format.json { render json: @registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registrations/1
  # PATCH/PUT /registrations/1.json
  def update
    respond_to do |format|
      if @registration.update(registration_params)
        format.html { redirect_to @registration, notice: 'Registration was successfully updated.' }
        format.json { render :show, status: :ok, location: @registration }
      else
        format.html { render :edit }
        format.json { render json: @registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registrations/1
  # DELETE /registrations/1.json
  def destroy
    @registration.destroy
    respond_to do |format|
      format.html { redirect_to registrations_url, notice: 'Registration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registration
      @registration = Registration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registration_params
      params.require(:registration).permit(:name, :email, :college, :event_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/fests_helper.rb
module FestsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :entry_fee %><br>
    <%= f.number_field :entry_fee %>
  </div>
  <div class="field">
    <%= f.label :start_datetime %><br>
    <%= f.datetime_select :start_datetime %>
  </div>
  <div class="field">
    <%= f.label :end_datetime %><br>
    <%= f.datetime_select :end_datetime %>
  </div>
  <div class="field">
    <%= f.label :no_participants %><br>
    <%= f.number_field :no_participants %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :fest_id %><br>
    <%= f.collection_select :fest_id, Fest.all, :id, :name, prompt: "Select Fest" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <h1 class="page-header">
                    Listing Events
                    <small><%= Event.count %></small>
                </h1>
            

              <% @events.each do |event| %> 
                <h2>
                    <%= link_to event.name, event_path(event.id) %>
                </h2>
                <p class="lead">
                    in <%= Fest.find(event.fest_id).name %>
                </p>
                <p><span class="glyphicon glyphicon-time"></span> on <%= event.start_datetime.strftime("%A, %d %B %Y %H:%M %p") %></p>
                <hr>
                <img class="img-responsive" src="http://placehold.it/900x300" alt="">
                <hr>
                <p><%= event.description %></p>

                <%= link_to event_path(event.id), class: "btn btn-primary" do %>
                 Read More <span class="glyphicon glyphicon-chevron-right"></span>
                <% end %>

            
                <hr>

                <% end %>

                <!-- Pager -->
                <ul class="pager">
                    <li class="previous">
                        <a href="#">&larr; Older</a>
                    </li>
                    <li class="next">
                        <a href="#">Newer &rarr;</a>
                    </li>
                </ul>

            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Listing Fests</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                            <% Fest.all.each do |fest| %>
                                <li><%= link_to fest.name %></li>
                            <% end %>
                             
                            </ul>
                        </div>
                       
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>

        </div>
        <!-- /.row -->

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">

                <!-- Blog Post -->

                <!-- Title -->
                <h1><%= @event.name %></h1>

                <!-- Author -->
                <p class="lead">
                    by <%= Fest.find(@event.fest_id).name %>
                </p>

                <hr>

                <!-- Date/Time -->
                <p>
                <span class="glyphicon glyphicon-time"></span> <%= @event.start_datetime.strftime("%A, %d %b %Y %H:%M %p") %>

                 <span class="glyphicon glyphicon-euro"></span> <%= @event.entry_fee %>

                 <span class="glyphicon glyphicon-user"></span> 100


                </p>

                <hr>

                <ol class="breadcrumb">
  <li><a href="/fests">Fests</a></li>
  <li><a href="/events">Events</a></li>
  <li class="active"><%= @event.name %></li>
</ol>

                <!-- Preview Image -->
                <img class="img-responsive" src="http://placehold.it/900x300" alt="">

                <hr>

                <!-- Post Content -->
               
               
                <p><%= @event.description %>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

                <hr>

                <!-- Blog Comments -->

                <!-- Comments Form -->
                <div class="well">
                    <h3>Register Here </h3>
<% @registration = Registration.new %>
<%= form_for(@registration) do |form| %>
  <% if @registration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@registration.errors.count, "error") %> prohibited this registration from being saved:</h2>
      <ul>
      <% @registration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :email %><br>
    <%= form.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :college %><br>
    <%= form.text_field :college, class: "form-control" %>
  </div>
    <%= form.hidden_field :event_id, value: @event.id %>
  <div class="form-groups">
    <%= form.submit "Register here", class: "btn btn-primary" %>
  </div>
<% end %>

                </div>

                <hr>

                <!-- Posted Comments -->

                <!-- Comment -->
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="http://placehold.it/64x64" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Start Bootstrap
                            <small>August 25, 2014 at 9:30 PM</small>
                        </h4>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                    </div>
                </div>

                <!-- Comment -->
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="http://placehold.it/64x64" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Start Bootstrap
                            <small>August 25, 2014 at 9:30 PM</small>
                        </h4>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                        <!-- Nested Comment -->
                        <div class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object" src="http://placehold.it/64x64" alt="">
                            </a>
                            <div class="media-body">
                                <h4 class="media-heading">Nested Start Bootstrap
                                    <small>August 25, 2014 at 9:30 PM</small>
                                </h4>
                                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                            </div>
                        </div>
                        <!-- End Nested Comment -->
                    </div>
                </div>

            </div>


      <div class="col-md-4">
        <div class="well">
          <h2>Registrations</h2>
          <ul>
            <% Registration.where('event_id = ?', @event.id ).each do |registration| %>
              <li><%= registration.name %></li>
            <% end %>
          </ul>
        </div>
      </div>
           
        </div>
        <!-- /.row -->



<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/fests/_form.html.erb
<%= form_for(@fest) do |f| %>
  <% if @fest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fest.errors.count, "error") %> prohibited this fest from being saved:</h2>

      <ul>
      <% @fest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fests/edit.html.erb
<h1>Editing Fest</h1>

<%= render 'form' %>

<%= link_to 'Show', @fest %> |
<%= link_to 'Back', fests_path %>

app/views/fests/index.html.erb
<div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <h1 class="page-header">
                    Listing Fests
                    <small><%= Fest.count %></small>
                </h1>
            

              <% @fests.each do |fest| %> 
                <h2>
                    <%= link_to fest.name, fest_path(fest.id) %>
                </h2>
                
                <p><span class="glyphicon glyphicon-time"></span> on <%= fest.start_date.strftime("%A, %d %B %Y %H:%M %p") %></p>
                <hr>
                <img class="img-responsive" src="http://placehold.it/900x300" alt="">
                <hr>
                <p><%= fest.description %></p>

                <%= link_to fest_path(fest.id), class: "btn btn-primary" do %>
                 Read More <span class="glyphicon glyphicon-chevron-right"></span>
                <% end %>

            
                <hr>

                <% end %>

                <!-- Pager -->
                <ul class="pager">
                    <li class="previous">
                        <a href="#">&larr; Older</a>
                    </li>
                    <li class="next">
                        <a href="#">Newer &rarr;</a>
                    </li>
                </ul>

            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Listing Fests</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                            <% Fest.all.each do |fest| %>
                                <li><%= link_to fest.name %></li>
                            <% end %>
                             
                            </ul>
                        </div>
                       
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>

        </div>
        <!-- /.row -->

<%= link_to 'New Fest', new_fest_path %>

app/views/fests/new.html.erb
<h2>Add Fest</h2>

<%= form_for @fest do |f| %>

<% if @fest.errors.any? %>
	<h3>These errors stopped the form from being saved : </h3>
	<ul>	
		<% @fest.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<label>Name</label><br/>
<%= f.text_field :name %> 
<p id="nameError"> </p>
<br/>
<label>Description: </label><br/>
<%= f.text_area :description, rows: 10, cols: 25 %><br/>
<label>Start Date </label><br/>
<%= f.date_field :start_date %><br/>
<label>End Date </label><br/>
<%= f.date_field :end_date %><br/>

<%= f.submit %>
<% end %>
<a href="/fests">List Fests </a>

<script>
var nameHandle = document.getElementById('fest_name');
var nameErrorHandle = document.getElementById('nameError');
nameHandle.onblur = function(){
	if(nameHandle.value.length == 0){
		nameErrorHandle.innerHTML = " Can't be blank";
	} else {
		nameErrorHandle.innerHTML = "";
	}
};
</script>

app/views/fests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fest.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @fest.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @fest.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @fest.end_date %>
</p>

<%= link_to 'Edit', edit_fest_path(@fest) %> |
<%= link_to 'Back', fests_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Festo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="../css/bootstrap.min.css" rel="stylesheet">
	<link href="../css/blog-home.css" rel="stylesheet">
	<script src="../js/jquery.js"></script>
   <!-- Bootstrap Core JavaScript -->
  <script src="../js/bootstrap.min.js"></script>

</head>
<body>

	 <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/fests">Festo</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/fests">Fests</a>
                    </li>
                    <li>
                        <a href="/events">Events</a>
                    </li>
                    <li>
                        <a href="/registrations">Registrations</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

	<div class="container">
		<%= yield %>
	</div>

</body>
</html>